name: alchemy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

module:
  androidX: true 


dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.19+2 
  provider: ^3.1.0
  http: ^0.12.0+2
  flutter_markdown:
    git:
        url: https://github.com/simpleclub/flutter_markdown.git
        ref: alignment
  html2md: ^0.5.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/ingredients/
   - assets/effects/
   - assets/bg/
   - assets/